# Generated by Django 5.1.3 on 2024-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(choices=[(True, 'Множественный выбор'), (False, 'Одиночный выбор')], default=False),
        ),
    ]
