# Generated by Django 5.1.3 on 2024-11-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_multiple_choice',
            field=models.CharField(choices=[('single', 'Один ответ'), ('multiple', 'Множественный выбор')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
